---
global:
  pattern: opea-chatqna-on-amd
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  amd_llm:
    namespace: amd-llm
    build_envs: []
    runtime_envs: []
  build:
    enabled: true

  genAiComps:
    gitUri: https://github.com/opea-project/GenAIComps.git
    gitRef: af3ff62
  genAIExamples:
    gitUri: https://github.com/opea-project/GenAIExamples.git
    gitRef: 61a8bef
    # Testing out old id
#    gitRef: ff66600

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true

