global:
  amdllm:
    namespace: amd-llm

external_cert_enabled: true # if true, values-secret should instantiate a matching vault secret source!

secret:
  hugging_face:
    ocp:
      secret_name: hf-token-secret
      key: huggingface
    vault:
      secret_name: huggingface
      path: secret/hub/huggingface
      key: token
  rhoai_model:
    ocp:
      secret_name: rhoai-model-secret
      key: inference_endpoint
    vault:
      secret_name: rhoai_model
      path: secret/hub/rhoai_model
      key: inference_endpoint
  endpoint_cert:
    ocp:
      secret_name: endpoint-cert
      key: bundle.crt
    vault:
      secret_name: endpoint_cert
      path: secret/hub/endpoint_cert
      key: bundle.crt

secret_store:
  name: vault-backend
  kind: ClusterSecretStore
