odf:
  namespace: openshift-storage
  storageClass:
    name: ocs-storagecluster-ceph-rgw
    objectStoreName: ocs-storagecluster-cephobjectstore

route:
  name: s3-rgw
  service:
    name: rook-ceph-rgw-ocs-storagecluster-cephobjectstore
    weight: 100
  port:
    targetPort: http

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
  awsimage: amazon/aws-cli

global:
  namespace: amd-pattern

rgw:
  cpu: 2
  memory: 8Gi
  bucketName: model-bucket

serviceAccountName: amd-pattern-sa
rbac:
  roles:
    - name: amd-pattern-role
      createRole: true
      apiGroups:
        - '""'
        - '"apps"'
        - '"machineconfiguration.openshift.io"'
        - '"rbac.authorization.k8s.io"'
        - '"security.openshift.io"'
        - '"ocs.openshift.io"'
        - '"route.openshift.io"'
      scope:
        cluster: true
      resources:
        - namespaces
        - secrets
        - storageclusters
        - routes
      verbs:
        - "create"
        - "get"
        - "list"
        - "patch"
        - "update"
        - "use"
  roleBindings:
    - name: amd-pattern-rolebind
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: amd-pattern-sa
        namespace: openshift-storage
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: amd-pattern-role