apiVersion: v1
kind: ConfigMap
metadata:
  name: create-rhoai-istio-rootca-cert-secret
  namespace: {{ .Values.global.amdllm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  create-rhoai-istio-rootca-cert-secret.sh: |
    #!/bin/bash
    echo "Starting secret sync script"

    UPSTREAM_EXISTS=$(oc get secret --ignore-not-found -n istio-system knative-serving-cert)
    EXISTS=$(oc get secret --ignore-not-found rhoai-ca-bundle)

    if [[ -z "${UPSTREAM_EXISTS}" ]]; then
      echo "upstream found"
    else
      echo "upstream not found"
    fi

    if [[ -z "${EXISTS}" ]]; then
      echo "creating secret..."
      oc create secret generic -n {{ .Values.global.amdllm.namespace }} rhoai-ca-bundle --from-literal=tls.crt="$(oc extract secret/knative-serving-cert -n istio-system --to=- --keys=tls.crt)"
      echo "done creating secret."
      exit
    else
      echo "oc get secret --ignore-not-found rhoai-ca-bundle returned non-empty string, not creating a secret"
    fi

    echo "script bottom"
