# script to pull the serving certificate set up for KNative and make available in case we want to secure a hosted LLM endpoint
# not necessarily needed without OPEA, but AMD may wish for something similar, not sure
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-rhoai-istio-rootca-cert-secret
  namespace: {{ .Values.global.amdllm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  create-rhoai-istio-rootca-cert-secret.sh: |
    #!/bin/bash
    echo "Starting secret sync script"

    UPSTREAM_EXISTS=$(oc get secret --ignore-not-found -n istio-system knative-serving-cert)
    EXISTS=$(oc get secret --ignore-not-found -n {{ .Values.global.amdllm.namespace }} rhoai-ca-bundle)

    if [[ -z "${UPSTREAM_EXISTS}" ]]; then
      echo "upstream secret in istio-system required for copy, but not found"
      exit 1
    fi

    if [[ -z "${EXISTS}" ]]; then
      echo "creating secret..."
      oc create secret generic -n {{ .Values.global.amdllm.namespace }} rhoai-ca-bundle --from-literal=tls.crt="$(oc extract secret/knative-serving-cert -n istio-system --to=- --keys=tls.crt)"
      echo "done."
    else
      echo "updating secret..."
      oc create secret generic -n {{ .Values.global.amdllm.namespace }} rhoai-ca-bundle --dry-run=client -o yaml --from-literal=tls.crt="$(oc extract secret/knative-serving-cert -n istio-system --to=- --keys=tls.crt)" | oc replace -f -
      echo "done."
    fi

    exit 0
