# not necessary without OPEA, used to pull OPEA llm and tei component models
# neither of these secret are necessary, but I was reluctant to fully drop the init-secret directory as it's possibly
# tied into Argo? Needs a "try it and see" approach to see if absolutely necessary for inclusion.
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.hugging_face.ocp.secret_name }}
  namespace: {{ .Values.global.amdllm.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secret_store.name }}
    kind: {{ .Values.secret_store.kind }}
  target:
    name: {{ .Values.secret.hugging_face.ocp.secret_name }}
    template:
      type: Opaque
  data:
    - secretKey: {{ .Values.secret.hugging_face.ocp.key }}
      remoteRef:
        key: {{ .Values.secret.hugging_face.vault.path }}
        property: {{ .Values.secret.hugging_face.vault.key }}
